# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Smart Green Campus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: make application-jwt.yml
      run:
        cd ./src/main/resources
        touch ./application-jwt.yml
        
        echo "${{ secrets.HARANG_JWT }}" >> ./application-jwt.yml
        
        cat ./application-jwt.yml
      
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle 
      run: ./gradlew build -x test
